#!/bin/sh

if [[ $1 == '' ]]; then
    echo 'usage: runserveronlinux <binary>'
    exit 1
else
    TARGET="$1"
fi

docker run --rm -it -v "$(pwd)":/current -p 127.0.0.1:2137:2137 -w /current mkorman/bionic-with-socat socat tcp-listen:2137,reuseaddr,fork, exec:"stdbuf -i0 -o0 -e0 $TARGET"
